function GraphSIM_score = GraphSIM_jnd( pcA, pcB,pc_fast,NPMapsA,NPMapsB)   
% name_fast: the keypoint resampling of point cloud, generated by demo_fast_make.m
% name_r: reference point cloud
% name_d: distorted point cloud
% r_b: blurring radius
% r_s£ºshrinking rate
% scale: the number of scales that are fused into a multiscale score
% clear
% name_fast = ('redandblack10000_4.ply');
% name_r = ('redandblack.ply'); 
% name_d = ('redandblack_0_0.ply'); 
r_b = 1/2; 
r_s = 1/3; 
% n_s = 3;

tic;
T = 0.001;
%rng(0)

% pc_fast = pcread(name_fast);
% pc_r = pcread(name_r);
% pc_d = pcread(name_d);
%% Neighbor Dimension
pc_r_coor = pcA.Location;
pc_d_coor = pcB.Location;
pc_fast_coor = pc_fast.Location;
idxA=find(NPMapsA(:,2)==0);
idxB=find(NPMapsB(:,2)==0);
NPMapsA(idxA,2)=1;
NPMapsB(idxB,2)=1;
pcA = pcReformByNpMaps(pcA,[],pc_r_coor);%delete points
pcB = pcReformByNpMaps(pcB,[],pc_d_coor);
pc_fast=pcReformByNpMaps(pc_fast,[],pc_fast_coor);
pc_r_coor = pcA.Location;
pc_d_coor = pcB.Location;
NPA=NPMapsA(:,1)./NPMapsA(:,2);
NPB=NPMapsB(:,1)./NPMapsB(:,2);

max_x = max(pc_r_coor(:,1)) - min(pc_r_coor(:,1));
max_y = max(pc_r_coor(:,2)) - min(pc_r_coor(:,2));
max_z = max(pc_r_coor(:,3)) - min(pc_r_coor(:,3));
box = [max_x, max_y, max_z];
epsilon = floor(min(box)/10);
r = pc_fast.Count;
sample_LMN = cell(r,1);

[idx, dit] = rangesearch(pc_r_coor, pc_fast_coor, epsilon);
[idx_d, dit_d] = rangesearch(pc_d_coor, pc_fast_coor, epsilon);


for s = 1:r
    %% graph creation
    [G, pointset, center, weight, radius,idx_graph_A] = graphcreation_radius_jnd(pcA, pc_fast, idx{s,1}, dit{s,1}, s, r_b);
    [G_d, pointset_d, center_d, weight_d, radius_d,idx_graph_B] = graphcreation_radius_jnd(pcB, pc_fast, idx_d{s,1}, dit_d{s,1}, s, r_b);

    %% similarity computation 
    feature_LMN = computeSimilarity_jnd(pointset, pointset_d, center, center_d, weight, weight_d, T,NPA,NPB,idx_graph_A,idx_graph_B);
    
    sample_LMN{s,1}=feature_LMN;

   
end
L=6;M=1;N=1;
%% compute GraphSIM at different scales 
GraphSIM_score=cal_mos(sample_LMN,L,M,N);

toc;